### ISSUE TITLE
CMUDict not defined

### ISSUE THREAD

**Issue by AfrahAsif** [libindic/Transliteration#20]
from transliteration import getInstance
t = getInstance()
text = u"ನಮಸ್ಕಾರ"
t_text = t.transliterate(text, "ml_IN")
print (t_text) #"നമസ്കാര"

On running this code in Python 3.6, the following error occurs,

NameError: name 'CMUDict' is not defined

**Comment by asdofindia** [comment]
Unable to reproduce this. I've updated the README with instructions on how to set up the project. Please follow that and let me know if the issue persists.
