### ISSUE TITLE
No module named 'normalizer'

### ISSUE THREAD

**Issue by achyutjoshi** [libindic/Transliteration#21]
Hi!

I was trying to use this package but I encountered this error. I could not find any file named 'normalizer' too.

ModuleNotFoundError: No module named 'normalizer'

Am I missing something?

Thanks!

**Comment by maheshuligade** [comment]
Hi @achyutjoshi ,
You need to install  `normalizer` using command `pip install normalizer`. @[Check Here](https://pypi.org/project/normalizer/)

**Comment by asdofindia** [comment]
I've updated the README to include information on how to setup virtual environment. Hope that's useful.
