### ISSUE TITLE
Transliteration from English does not work

### ISSUE THREAD

**Issue by GokulNC** [libindic/Transliteration#24]
Example:
```
>>> from libindic.transliteration import getInstance
>>> t = getInstance()
>>> text = "google"
>>> t_text = t.transliterate(text, "ml_IN")
>>> print(t_text)
google
```

But it seems to work for some words, but breaks:
```
>>> t.transliterate('india', "ml_IN")
'ഇന്\u200dഡീഅ '
```

Could it be because there is no rule-based mapping defined for "g" and "d" for Malayalam?
If so, what do we generally do in cases like this?

**Comment by GokulNC** [comment]
Forgot to mention, I'm on Python 3.7.3 and latest commit 475b14f of this repo.

**Comment by asdofindia** [comment]
This transliteration library is dependent on the CMU dictionary. We should have a generic transliterator I agree. https://github.com/knadh/ml2en is a useful reference.
