### ISSUE TITLE
http://silpa.org.in/Transliteration is down

### ISSUE THREAD

**Issue by arunasank** [libindic/Transliteration#7]
I have been trying to access http://silpa.org.in/Transliteration and I get a "503 Service Unavailable" error.

**Comment by copyninja** [comment]
Yes it is down after I upgraded my VPS but I didn't get time to have a look. @stultus were you able to check what is wrong?.

**Comment by asdofindia** [comment]
No longer relevant. The site is available on libindic.org/Transliteration
